CREATE TABLE telegram_groups (
    id SERIAL PRIMARY KEY,
    telegram_group_id BIGINT UNIQUE NOT NULL,
    title VARCHAR(500) NOT NULL,
    username VARCHAR(255),
    type VARCHAR(50) NOT NULL,
    description TEXT,
    members_count INTEGER DEFAULT 0,
    photo_url TEXT,
    is_public BOOLEAN DEFAULT true,
    verified BOOLEAN DEFAULT false,
    invite_link TEXT,
    language VARCHAR(10) DEFAULT 'unknown',
    region VARCHAR(100) DEFAULT 'unknown',
    category VARCHAR(100) DEFAULT 'General',
    imported_by UUID NOT NULL,
    import_status VARCHAR(50) DEFAULT 'pending',
    imported_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);